# Generated by Django 2.0 on 2018-10-25 01:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20181024_0541'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'participant')},
        ),
    ]
